import { useQuery } from '@tanstack/react-query'
import { entriesApi, Entry, SearchResult } from '@/lib/api'
import { useAuth } from '@/contexts/AuthContext'

/**
 * Hook to fetch a list of entries with pagination
 */
export function useEntries(skip = 0, limit = 100) {
  const { user, loading } = useAuth()

  return useQuery<Entry[]>({
    queryKey: ['entries', skip, limit],
    queryFn: () => entriesApi.list(skip, limit),
    enabled: !loading && !!user,
  })
}

/**
 * Hook to fetch a single entry by ID
 */
export function useEntry(id: number, enabled = true) {
  const { user, loading } = useAuth()

  return useQuery<Entry>({
    queryKey: ['entry', id],
    queryFn: () => entriesApi.get(id),
    enabled: enabled && !!id && !loading && !!user,
  })
}

/**
 * Hook to fetch entries semantically related to the given entry.
 *
 * Returns an empty array while the entry's embedding is still being
 * generated by the async Celery job. Stale embeddings are tolerated —
 * React Query handles refetching on focus.
 */
export function useRelatedEntries(id: number, k = 3, enabled = true) {
  const { user, loading } = useAuth()

  return useQuery<SearchResult[]>({
    queryKey: ['entry', id, 'related', k],
    queryFn: () => entriesApi.getRelated(id, k),
    enabled: enabled && !!id && !loading && !!user,
    staleTime: 60_000,
  })
}
